package(default_visibility = ["//visibility:public"])

py_library(
    name = "lib",
    srcs = ["__init__.py", ],
    deps = [
        "//recordio/recordio:lib",
        "//recordio/torch_dataset:lib",
        "//recordio/tensorflow_op:lib",
    ]
)
